from __future__ import annotations

KR_RSS_FEEDS = [
    ("보안뉴스", "https://www.boannews.com/media/news_rss.xml"),
    ("데일리시큐", "https://www.dailysecu.com/rss/allArticle.xml"),
    (
        "Google News 국내 보안",
        "https://news.google.com/rss/search?q=(%ED%95%9C%EA%B5%AD+OR+%EA%B5%AD%EB%82%B4+OR+KISA)+%EB%B3%B4%EC%95%88+when:1d&hl=ko&gl=KR&ceid=KR:ko",
    ),
    (
        "Google News 보안",
        "https://news.google.com/rss/search?q=%EB%B3%B4%EC%95%88+when:1d&hl=ko&gl=KR&ceid=KR:ko",
    ),
    (
        "Google News NAC EDR",
        "https://news.google.com/rss/search?q=NAC+OR+EDR+when:1d&hl=ko&gl=KR&ceid=KR:ko",
    ),
    (
        "Google News 지니언스",
        "https://news.google.com/rss/search?q=%EC%A7%80%EB%8B%88%EC%96%B8%EC%8A%A4+when:1d&hl=ko&gl=KR&ceid=KR:ko",
    ),
    (
        "Google News 제로트러스트",
        "https://news.google.com/rss/search?q=%EC%A0%9C%EB%A1%9C%ED%8A%B8%EB%9F%AC%EC%8A%A4%ED%8A%B8+when:1d&hl=ko&gl=KR&ceid=KR:ko",
    ),
    (
        "Google News SSL VPN",
        "https://news.google.com/rss/search?q=%22SSL+VPN%22+OR+%22SSLVPN%22+when:1d&hl=ko&gl=KR&ceid=KR:ko",
    ),
    (
        "Google News Network Access Control",
        "https://news.google.com/rss/search?q=%22Network+Access+Control%22+OR+%22%EB%84%A4%ED%8A%B8%EC%9B%8C%ED%81%AC+%EC%A0%91%EA%B7%BC%EC%A0%9C%EC%96%B4%22+when:1d&hl=ko&gl=KR&ceid=KR:ko",
    ),
]

FOCUS_RSS_FEEDS = [
    (
        "GN NAC",
        "https://news.google.com/rss/search?q=%22Network+Access+Control%22+OR+%22NAC%22+cybersecurity+when:1d&hl=en-US&gl=US&ceid=US:en",
    ),
    (
        "GN EDR",
        "https://news.google.com/rss/search?q=%22Endpoint+Detection+and+Response%22+OR+EDR+when:1d&hl=en-US&gl=US&ceid=US:en",
    ),
    (
        "GN SSL VPN",
        "https://news.google.com/rss/search?q=%22SSL+VPN%22+OR+%22remote+access+VPN%22+when:1d&hl=en-US&gl=US&ceid=US:en",
    ),
    (
        "GN Zero Trust",
        "https://news.google.com/rss/search?q=%22Zero+Trust%22+OR+ZTNA+when:1d&hl=en-US&gl=US&ceid=US:en",
    ),
    (
        "GN Genians",
        "https://news.google.com/rss/search?q=Genians+OR+%EC%A7%80%EB%8B%88%EC%96%B8%EC%8A%A4+when:1d&hl=en-US&gl=US&ceid=US:en",
    ),
]

GLOBAL_RSS_FEEDS = [
    ("The Hacker News", "https://feeds.feedburner.com/TheHackersNews"),
    ("BleepingComputer", "https://www.bleepingcomputer.com/feed/"),
    ("Dark Reading", "https://www.darkreading.com/rss.xml"),
    ("Krebs on Security", "https://krebsonsecurity.com/feed/"),
    ("SecurityWeek", "https://www.securityweek.com/feed/"),
    ("The Record", "https://therecord.media/feed"),
    ("CyberScoop", "https://cyberscoop.com/feed/"),
    ("SC Media", "https://www.scmagazine.com/feed"),
    ("Help Net Security", "https://www.helpnetsecurity.com/feed/"),
    ("The Register", "https://www.theregister.com/security/headlines.atom"),
    ("Wired Security", "https://www.wired.com/feed/category/security/latest/rss"),
    ("Ars Technica Security", "https://feeds.arstechnica.com/arstechnica/security"),
    ("CSO Online", "https://www.csoonline.com/feed/"),
    ("CISA", "https://www.cisa.gov/cybersecurity-advisories/all.xml"),
    ("Microsoft Security", "https://www.microsoft.com/en-us/security/blog/feed/"),
    ("Cisco Talos", "https://blog.talosintelligence.com/rss/"),
    ("Palo Alto Unit 42", "https://unit42.paloaltonetworks.com/feed/"),
    ("Reuters Technology", "https://feeds.reuters.com/reuters/technologyNews"),
    ("BBC Technology", "https://feeds.bbci.co.uk/news/technology/rss.xml"),
]

KR_DOMAINS = (
    "boannews.com",
    "dailysecu.com",
    "zdnet.co.kr",
    "etnews.com",
    "thelec.kr",
    "it.chosun.com",
    "digitaltoday.co.kr",
    "bloter.net",
    "byline.network",
    "platum.kr",
    "inews24.com",
    "mt.co.kr",
    "mk.co.kr",
    "hankyung.com",
    "yna.co.kr",
    "yonhapnews.co.kr",
    "newsis.com",
    "news1.kr",
    "donga.com",
    "joongang.co.kr",
    "joins.com",
    "hani.co.kr",
    "khan.co.kr",
    "kisa.or.kr",
    "krcert.or.kr",
    "pipc.go.kr",
    "mss.go.kr",
    "korea.kr",
    "fnnews.com",
    "sedaily.com",
    "businesspost.co.kr",
    "datanet.co.kr",
    "itdaily.kr",
    "securityworld.kr",
    "comworld.co.kr",
    "hellot.net",
    "wowtv.co.kr",
    "edaily.co.kr",
    "asiae.co.kr",
    "news.samsung.com",
    "ahnlab.com",
    "estsecurity.com",
    "genians.co.kr",
    "genians.com",
)

GLOBAL_DOMAINS = (
    "thehackernews.com",
    "bleepingcomputer.com",
    "darkreading.com",
    "krebsonsecurity.com",
    "securityweek.com",
    "therecord.media",
    "cyberscoop.com",
    "scmagazine.com",
    "scworld.com",
    "helpnetsecurity.com",
    "theregister.com",
    "wired.com",
    "arstechnica.com",
    "csoonline.com",
    "cisa.gov",
    "microsoft.com",
    "talosintelligence.com",
    "paloaltonetworks.com",
    "reuters.com",
    "bbc.co.uk",
    "bbc.com",
    "techcrunch.com",
    "zdnet.com",
    "computerweekly.com",
    "infosecurity-magazine.com",
    "recordedfuture.com",
    "mandiant.com",
    "crowdstrike.com",
    "sentinelone.com",
    "fortinet.com",
    "cisco.com",
    "nist.gov",
    "enisa.europa.eu",
    "ncsc.gov.uk",
    "wsj.com",
    "ft.com",
    "bloomberg.com",
    "nytimes.com",
    "theguardian.com",
    "cnn.com",
    "apnews.com",
    "gartner.com",
    "idc.com",
    "forrester.com",
)
